### ISSUE TITLE
Fix running game in the console:

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-ai-cs/rl-lab#3]
```zsh
➜ python environment.py maps/easiest.txt
INFO:root:Loading map: maps/easiest.txt
It will converge at 0.001
Traceback (most recent call last):
  File "environment.py", line 159, in <module>
    agt.train(env)
  File "/Users/meneguzzi/Documents/pucrs/courses/2021-1/undergrad/AI for CS/coursework/notebooks/rl-lab/link_ref.py", line 48, in train
    action = self.get_action(self.state)
  File "/Users/meneguzzi/Documents/pucrs/courses/2021-1/undergrad/AI for CS/coursework/notebooks/rl-lab/link_ref.py", line 79, in get_action
    return get_action(self,state)
NameError: name 'get_action' is not defined
```

**Comment by meneguzzi** [comment]
This error is primarily due to this being empty, stupidity on my part.
